from typing import Any

class Tensor:
    def cpu(self) -> Tensor: ...
    def numpy(self) -> Any: ...
    def to(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def float(self) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    @property
    def shape(self) -> tuple[int, ...]: ...

class device:
    def __init__(self, device: str) -> None: ...

class dtype:
    half: Any
    float16: Any

class cuda:
    @staticmethod
    def is_available() -> bool: ...

class _InferenceMode:
    def __init__(self, mode: bool = True) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...

def inference_mode(mode: bool = True) -> _InferenceMode: ...

def manual_seed(seed: int) -> None: ...
def randint(low: int, high: int, size: tuple[int, ...], *, dtype: Any = ...) -> Tensor: ...
def from_numpy(arr: Any) -> Tensor: ...
def tensor(data: Any, *, dtype: Any = None, device: Any = None) -> Tensor: ...
def no_grad() -> Any: ...

half: Any
float16: Any
long: Any
