from collections.abc import Callable, Iterator, Sequence
from typing import Any

import mlx.core as mx

class Module:
    _exl3_engine: str | None
    _exl3: Any
    _huge: bool
    _draft_head: Any
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameters(self) -> dict[str, mx.array]: ...
    def trainable_parameters(self) -> dict[str, mx.array]: ...
    def update(self, parameters: dict[str, mx.array]) -> None: ...
    def eval(self) -> Module: ...
    def train(self) -> Module: ...
    def freeze(self, **kwargs: Any) -> Module: ...
    def unfreeze(self, **kwargs: Any) -> Module: ...
    def save_weights(self, file: str) -> None: ...
    def load_weights(self, file: str, strict: bool = True) -> Module: ...
    def children(self) -> Iterator[Module]: ...
    def modules(self) -> Iterator[Module]: ...
    def named_modules(self) -> Iterator[tuple[str, Module]]: ...
    def apply(self, map_fn: Callable[[Module], None]) -> None: ...
    def apply_to_modules(self, apply_fn: Callable[[str, Module], Module | None]) -> Module: ...
    def state(self) -> dict[str, Any]: ...
    def update_modules(self, modules: dict[str, Module]) -> None: ...

class Linear(Module):
    weight: mx.array
    bias: mx.array | None
    def __init__(self, input_dims: int, output_dims: int, bias: bool = True) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...

class QuantizedLinear(Module):
    weight: mx.array
    bias: mx.array | None
    scales: mx.array
    biases: mx.array
    group_size: int
    bits: int
    mode: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
    @classmethod
    def from_linear(cls, linear: Linear, *, group_size: int, bits: int) -> QuantizedLinear: ...

def silu(x: mx.array) -> mx.array: ...
def gelu(x: mx.array) -> mx.array: ...
def relu(x: mx.array) -> mx.array: ...
def gelu_approx(x: mx.array) -> mx.array: ...
def gelu_fast_approx(x: mx.array) -> mx.array: ...
