from typing import Any, Iterator

class _SafeSlice:
    def get_tensor(self, name: str) -> Any: ...

class safe_open:
    def __init__(self, filename: str, framework: str = "pt", device: str = "cpu") -> None: ...
    def keys(self) -> list[str]: ...
    def get_tensor(self, name: str) -> Any: ...
    def __getitem__(self, name: str) -> _SafeSlice: ...
    def __enter__(self) -> safe_open: ...
    def __exit__(self, *args: Any) -> None: ...
