from typing import Any, Iterator

class Config:
    vocab_size: int
    @staticmethod
    def from_directory(path: str) -> Config: ...

class Model:
    fwd_modules: list[tuple[Any, Any, Any]]
    @staticmethod
    def from_config(config: Config) -> Model: ...
    def load(
        self,
        *,
        max_output_size: int,
        max_output_factor: int,
        progressbar: bool = True,
    ) -> None: ...
    def forward(self, input_ids: Any, params: dict[str, Any] | None = None) -> Any: ...
    def prepare_inputs(self, input_ids: Any, params: dict[str, Any]) -> Any: ...
    def find_module(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
